### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by KuSh** [cnumr/ecoCode#104]
The project is licensed as GPL-3 which does not permit to use it in Sonarqube which is licensed under LGPL-3.0.

Refs:
- https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
- https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins

The fact that CodeNarc code project, which has an Apache-2.0 license, is included in the repository could also be a problem.

Ref: https://www.apache.org/licenses/GPL-compatibility.html

My reco:

Switch ecoCode plugins to LGPL-3.0 and preferably upstream modifications to CodeNarc or fork it as a separate project if not possible

regards,
Nicolas

**Comment by Silicoman** [comment]
To help and auditing licences, `mvn org.codehaus.mojo:license-maven-plugin:aggregate-add-third-party`  .

Not the first to asking about licence plugin. It's may also depends about fork plugins.
https://community.sonarsource.com/t/legal-concern-custom-rules-plugin-based-on-the-provided-template/51121/3
Example plugin are under MIT Licence. 

> The [GNU LGPL 3.0](https://www.gnu.org/licenses/lgpl.txt) license of this GitHub repository does not apply in the java-custom-rules-example directory. All contents under the java-custom-rules-example directory are licensed under the more permissive [MIT No Attribution](https://github.com/SonarSource/sonar-java/blob/master/docs/java-custom-rules-example/LICENSE.txt) license.

So also it depends what we want about the ecocode project. (Copyleft ?)

**Comment by KuSh** [comment]
> I'm looking how it's interpreted by other sonar communities. If we are looking [top Github project](https://github.com/search?o=desc&q=sonar&s=stars&type=Repositories) ,there is [sonarqube-community-branch-plugin](https://github.com/mc1arke/sonarqube-community-branch-plugin) project with +1K stars. They are under GPL3 licence.

Being (a little bit) popular doesn't mean you're doing right ^^

> > How are the various GNU licenses compatible with each other? ([#AllCompatibility](https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility)) (https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility))
> Code developed (ecocode) under GPL3 can't use only GPL2-only.
Code developed (sonarqube) under LGPL3 can use GPL3

For me you're reading it wrongly. IANAL but the matrix says clearly that the combination of a LGPLv3 or later app (sonarqube) and a GPL lib / plugin (ecoCode) result is "OK: Combination is under GPLv3 [[8]](https://www.gnu.org/licenses/gpl-faq.en.html#compat-matrix-footnote-8). As you're not allowed to change the Sonarqube licence this means that you're not respecting its licence.

This should be checked with a lawyers or a FLOSS licence expert. I could be wrong (and would like to know it and why in that case ;) )

**Comment by Silicoman** [comment]
It's first time, i have to check this type of issue. Clearly, not the most funniest. ^^
I have opened [sonarsource topic](https://community.sonarsource.com/t/question-about-license-and-custom-plugin-gpl3-vs-lgpl3/64336) to have an other point of view.

The misunderstand is about  **Combination is under GPLv3,**. The GPL3 protects the project if someone decide to fork or to use our project outside our intentional usage. Example,  _sonarsource_  can't  integrate this plugin natively. No one can fork (sonarqube + ecocode) under an other license that GPL3.  

I find this definition that’s resume what i have actually understand.

> Whenever changes are made under GPL license, source codes are required and changes must also be licensed under GPL, while LGPL may allow non-GPL programs to link to libraries but must still provide source code

WIll see at sonarsource forum, if someone can light us.. before i use my contractual support joker.

**Comment by Silicoman** [comment]
> I’m no license expert either. But if you’re asking about eventual inclusion in the Marketplace, the [requirement](https://community.sonarsource.com/t/deploying-to-the-marketplace/35236) is that the license be " a known FLOSS one (check [the list provided by the Open Source Initiative)](http://opensource.org/licenses)"
So as long as the license is on that list, and GPL3 is, then you’re good.
HTH,

So gpl3 no problem.
