### ISSUE TITLE
Documentation of Java backend rules

### ISSUE THREAD

**Issue by wokier** [cnumr/ecoCode#143]
Hi

This page expose only the android java rules
https://www.ecocode.io/rules

But we have found and used other java rules that applies to java backend
https://github.com/cnumr/ecoCode/tree/main/src/java-plugin/src/main/java/fr/cnumr/java/checks

**Comment by olegoaer** [comment]
Hi,

_ecoCode_ was the former name of a research project only dedicated to Android. Today this is the name of the global project, but the website has not been updated yet. So everything is normal ^^
