### ISSUE TITLE
Quality gates and Quality profiles not visible

### ISSUE THREAD

**Issue by rhouma-eng** [cnumr/ecoCode#151]
I am trying to install ecocode on my environement.
I installed the plugins and i can confirm that the number of rules increased for JAVA , PHP and Python
![image](https://user-images.githubusercontent.com/47340462/185918078-7d4576fa-bab9-43a9-9289-ae85ec08530a.png)

But when i try to manage the quality gate and quality profile i can't see them at all

![image](https://user-images.githubusercontent.com/47340462/185918371-8371c288-3e1a-4e7c-8137-fc11afb827b0.png)
Sonarqube version: Community EditionVersion 8.9.9 (build 56886) running on Docker container .
Is there anyone who can help me on this please ?
Thanks.

**Comment by MP-Aubay** [comment]
Hi @rhouma-eng ,

I do not know if I understand exactly your problem but I will try to help you.

First thing, did you create a new quality profile or did you use the default (Sonar way) ? You need to create a new profile to add EcoCode rule.

To do so, you can copy an existing profile, and then choose "Activate More" to add EcoCode rules.

And when it is done, you need to modify your projet (in Sonar) to use this profile, or you set it as the default.

You do not need to modify Quality Gate.

Regards,
Mikaël

**Comment by rhouma-eng** [comment]
Thank you Mikaël , 
This fixed my issue .
