### ISSUE TITLE
Migration compilation to Java 11

### ISSUE THREAD

**Issue by MP-Aubay** [cnumr/ecoCode#164]
Java 8 is almost dead, long live Java 11 (even if Java 17 is already out).

Migrating plugins to Java 11 should be a good idea, as Sonarqube server already use Java 11 (https://docs.sonarqube.org/latest/requirements/requirements/).

(Not authorize to add label enhancement)

**Comment by jules-delecour-dav** [comment]
No constraint to use java 11 from my point of view

**Comment by glalloue** [comment]
@MP-Aubay : GO to migrate to java 11+ 
You can take the action if you want

**Comment by dedece35** [comment]
hello @MP-Aubay ,

I have just tested in local with last code in main branch with : 
- Sonar locally installed with docker
- push one local java API results to my local Sonar

All is ok for me, you can close this issue unless someone else wants to test it also.

**Comment by med-S** [comment]
Hello @MP-Aubay & @dedece35,

I have just retested the last merge #167 in the main branch. 
Sonar locally is working fine and all the rules are there (no error prompt). Tested also one local project in Sonar.

For me, we can close this issue since it's a duplicate.
