### ISSUE TITLE
Crash au lancement du container sonar

### ISSUE THREAD

**Issue by augustinde** [cnumr/ecoCode#169]
Hello,

Après avoir build le jar, je lance le docker compose mais pendant le lancement du container sonarqube, j'ai cette erreur : 
```

2022.11.04 09:21:10 WARN  web[][o.s.c.a.AnnotationConfigApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc-org.sonar.server.rule.RegisterRules': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/sonar/java/JavaVersionAwareVisitor
2022.11.04 09:21:10 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc-org.sonar.server.rule.RegisterRules': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/sonar/java/JavaVersionAwareVisitor
```

Précédé par ce log un peu plus haut : 
`INFO  web[][o.s.s.p.ServerPluginManager] Deploy ecoCode Java Sonar Plugin / 1.0.0-SNAPSHOT / null`

J'ai bien essayer de changer la version java pour build le jar mais rien n'y fait :/

**Comment by oussamaLaribi** [comment]
Hello Hugo, j’ai trouvé une solution pour le problème du lancement de sonar, c’est corrigé sur votre branch, en fait lors de l'écriture de règles Java personnalisées, vous ne pouvez utiliser que les classes du package org.sonar.plugins.java.api. Les autres packages ne sont pas exposés aux plug-ins personnalisés lors de l’exécution. (C’est le cas d’interface JavaVersionAwareVisitor).
