### ISSUE TITLE
Dependance Maven codenarc inconnue (v2.2.1)

### ISSUE THREAD

**Issue by Silicoman** [cnumr/ecoCode#47]
Holla,

Il est déclaré dans le projet la **dépendance codeNarc** en version 2.2.1 . Cette librairie n'existe pas/plus sur maven repository et empêche la construction du projet. Il faudrait soit **downgrade en 2.2.0 ou upgrade en 3.0.0**

Ref : https://mvnrepository.com/artifact/org.codenarc/CodeNarc

Je n'ai pas eu le temps de tester la modification à cause de la différenciation d'outillage Gradle vs Maven sur le module codenarc-converter.

**Comment by Silicoman** [comment]
Je n'ai pas bien compris le fork de codeNarc copier coller dans le dépot. En tout cas, entraine une complexité de gestion de dependance.
SI aucun changement, il faudrait integrer le plugin suivant https://github.com/raphw/gradle-maven-plugin pour executer le sous projet en tant que dependance/module. Cela permettrait de conserver la partie gradle dans le cycle de vie Maven du projet principal ecocode.

PI, des renommages de groupeID devornt être réaliser sur le codenarc car il est dangeureux de s'approprier un groupID+artifactID d'une dependence. (Risque de pull une dep d'un registre avec mauvais checksum, etc)

**Comment by jhertout** [comment]
Bonjour,

la version de codenarc utilisée a été modifiée avec des règles spécifiques et un profil spécifique pour le projet Android. En vrai je pense que ça devrait être un sous-module de la partie Android. mes connaissances en Maven étant ce qu'elles sont pour le moment ça a été rajouté pour que ça fonctionne et je conçois que ça complexifie le projet.
Je vais essayé de déplacer le module dans la partie Android et de mieux régler les dépendances. je prends toutes les suggestions à ce sujet !

**Comment by cyChop** [comment]
La pull request #83 contenait une modification de INSTALL.md qui visait à aider l'installation du projet, notamment sur la gestion de CodeNarc.

@Silicoman Des modifications ont bien été effectuées par rapport à la v2.2.0.

**Comment by dedece35** [comment]
@MP-Aubay, @olegoaer, @jhertout
please see ... my comment in https://github.com/cnumr/ecoCode/issues/170 about this subject
this issue is duplication about #149 and #170 for me.

**Comment by dedece35** [comment]
je pense qu'on peux fermer cette issue suite aux discussion et résolution dans la #170. non ? @MP-Aubay @Silicoman @jhertout
